--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/RealBJsingh/Better-Query
build-by-default: true
branches:
- main
projects:
  Better-Query:
    path: ""
    icon: "assets/icon.png"
...
